<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>ASM</string>
	</array>
	<key>name</key>
	<string>Assembly ICMC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(string|var|static)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.reg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:r0|r1|r2|r3|r4|r5|r6|r7|sp|fr|pc|ir|mar)\b</string>
			<key>name</key>
			<string>entity.name.function.reg</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z][a-z-A-Z0-9-_]+)\s*:</string>
			<key>name</key>
			<string>entity.name.section.label</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#([a-zA-Z])([a-zA-Z-_0-9]*)\W</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.values</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#(\d+)\D</string>
			<key>name</key>
			<string>constant.language.values</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.values</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#(\'.\'|\'\\.\')</string>
			<key>name</key>
			<string>constant.language.values</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\$)(['"])(.*)\1(?!\$)</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s?(;.*)$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.dec</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((0x|0X)[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.bin</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([0-1]+b)\b</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:add|addc|sub|subc|mul|mulc|div|divc|inc|dec|mod|rotl|rotr|shiftl0|shiftl1|shiftr0|shiftr1|and|or|xor|not|cmp|store|storei|load|loadi|mov|loadn|jmp|jeq|jne|jz|jnz|jc|jnc|jgr|jle|jeg|jql|jov|jno|jn|jdz|call|ceq|cne|cz|cnz|cc|cnc|cgr|cle|ceq|cel|cov|cno|cn|cdz|rts|inchar|outchar|push|pop|clearc|setc|halt|breakp|nop)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ICMC</string>
	<key>uuid</key>
	<string>fa635543-9751-4798-82a7-c8fb93470582</string>
</dict>
</plist>
