#line 1 "tokens.cpp"

#line 3 "tokens.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[238] =
    {   0,
        0,    0,    0,    0,   85,   83,   77,   77,   32,   83,
       16,   31,   83,   34,   35,   14,   13,   37,   12,   83,
       15,   67,   68,   38,   36,   27,    1,   28,   43,   65,
       65,   41,   42,   21,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   39,   22,   40,
       33,   82,   81,   82,   26,    0,   76,    0,    8,   40,
       29,    9,    0,    0,    6,   17,    4,   18,    5,   71,
       78,   79,    7,   72,   67,    0,    0,   67,   67,    0,
       67,   68,   68,   68,   68,   42,   39,   41,   20,   23,
       25,   24,   19,   65,    0,    0,   10,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   47,   65,
       65,   65,   65,   65,   65,   65,   11,   30,   80,   69,
        0,   71,   79,   71,    0,   72,    0,   70,   67,   67,
       67,   67,    0,   66,   68,   68,   68,   68,    3,    2,
       65,   65,   65,   65,   65,   65,   65,   65,   55,   65,
       65,   45,   65,   65,   65,   65,   65,   65,    0,   71,
        0,   71,    0,   72,   70,   67,   74,   75,   66,    0,
       66,   66,   68,   65,   65,   50,   44,   65,   65,   65,
       48,   65,   65,   54,   65,   65,   65,   65,   46,   65,
        0,   71,   74,    0,   74,   75,    0,   66,   66,    0,

       73,   66,   66,   57,   52,   58,   65,   65,   65,   63,
       65,   65,   65,   65,   56,    0,   74,   74,    0,    0,
       75,   73,   66,   62,   65,   65,   59,   64,   60,   61,
       49,    0,   74,   65,   51,   53,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   26,   26,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   30,   49,   50,   30,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       30,   30,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    6,
        7,    7,    6,    6,    1,    1,    1,    1,    6,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    7,
        6,    6,    7,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[246] =
    {   0,
        0,    0,   62,   63,  454,  455,  455,  455,  430,   62,
       45,   63,  416,  455,  455,  428,   59,  455,   58,   58,
       67,   84,  130,  426,  455,   73,  426,   61,  455,    0,
       83,  455,  455,  425,  420,  391,   40,  392,   44,  375,
       45,   55,  372,  375,   49,  357,  361,  455,   84,  455,
      455,  455,  455,  391,  455,  104,  455,    0,  455,  455,
      455,  455,  102,  398,  455,  455,  455,  455,  455,  138,
      455,    0,  455,  167,   77,  107,  102,   96,   82,  389,
      121,    0,  119,   92,  140,  455,  455,  455,  380,  455,
      455,  455,  379,    0,  126,  365,  455,  348,  355,  343,

      357,  345,  349,  338,  336,  334,  331,  330,    0,  329,
      336,  327,  342,  333,  332,  327,  455,  455,  455,  455,
      187,  455,    0,  190,  208,  455,  174,  212,  103,  455,
      341,  321,    0,  213,  132,  455,  338,  317,  455,  455,
      314,  321,  313,  302,  147,  310,  288,  286,    0,  284,
      273,    0,  272,  265,  259,  254,  255,  247,  196,  219,
      235,  455,  241,  254,  455,  455,  224,  236,  137,  276,
      150,  246,  455,  242,  242,    0,    0,  231,  236,  221,
        0,  222,  218,    0,  205,  188,  191,  191,    0,  188,
      263,  283,  455,  299,  274,  455,  317,  218,  455,  290,

      320,  193,  173,    0,  163,    0,  159,  129,  126,    0,
      130,  121,  122,  112,    0,  302,  323,  455,  341,  326,
      345,  455,  455,    0,   86,   83,    0,    0,    0,    0,
        0,  329,  360,   89,    0,    0,  455,  410,  417,  424,
      427,  434,  438,  125,  439
    } ;

static const flex_int16_t yy_def[246] =
    {   0,
      237,    1,  238,  238,  237,  237,  237,  237,  237,  239,
      237,  237,  240,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  241,
      241,  237,  237,  237,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  237,  237,  237,
      237,  237,  237,  237,  237,  239,  237,  239,  237,  237,
      237,  237,  240,  240,  237,  237,  237,  237,  237,  237,
      237,  242,  237,  237,   22,  237,  237,  237,  237,  243,
      237,   23,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  241,  239,  240,  237,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  237,  237,  237,  237,
      237,  237,  242,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  244,  243,  237,  237,  237,  237,  237,  237,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  237,  237,
      237,  237,  237,  237,  237,  237,  244,  245,  237,  237,
      237,  237,  237,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      237,  237,  237,  237,  245,  237,  237,  237,  237,  237,

      237,  237,  237,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  237,  237,  237,  237,  237,
      237,  237,  237,  241,  241,  241,  241,  241,  241,  241,
      241,  237,  237,  241,  241,  241,    0,  237,  237,  237,
      237,  237,  237,  237,  237
    } ;

static const flex_int16_t yy_nxt[520] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   30,   30,   30,
       31,   30,   30,   30,   32,    6,   33,   34,   35,   30,
       36,   37,   38,   39,   40,   41,   30,   42,   30,   30,
       30,   30,   43,   44,   45,   30,   30,   46,   47,   30,
       48,   49,   50,   51,   53,   53,   57,   59,   60,   61,
       66,   68,   54,   54,   70,   70,   70,   71,   87,  100,
       69,   67,   72,   92,   93,   62,  101,   95,  107,   73,
       96,  102,   88,  104,   89,   90,  108,   58,   74,  109,

       75,   75,   76,  105,  113,  110,  117,  114,   57,  120,
      237,   77,  131,  127,   78,  127,   79,   80,  128,  128,
      128,   74,  137,   76,   76,   76,  129,   77,  130,  167,
       57,  132,  236,   81,   77,  130,  237,   64,  235,   58,
       79,  138,  234,   80,   74,  118,   82,   82,   82,  135,
       77,  136,  130,  130,   70,   70,   70,   77,  231,  130,
       83,   58,   84,  230,  136,  121,  122,  198,  122,  199,
      129,  229,  136,   77,  228,  136,  227,  130,  226,   85,
      202,  121,  122,  124,  124,  124,   84,  122,  136,  135,
      128,  128,  128,  199,  125,  126,  136,  126,  159,  203,

      159,  178,  179,  160,  160,  160,  124,  124,  124,  225,
      125,  126,  160,  160,  160,  224,  126,  161,  162,  163,
      162,  163,  223,  223,  164,  164,  164,  168,  128,  128,
      128,  215,  214,  161,  162,  160,  160,  160,  213,  162,
      165,  212,  165,  169,  170,  171,  191,  122,  191,  122,
      199,  192,  192,  192,  193,  194,  165,  164,  164,  164,
      211,  165,  172,  122,  210,  170,  196,  197,  122,  171,
      164,  164,  164,  193,  199,  209,  194,  208,  199,  192,
      192,  192,  126,  207,  126,  196,  206,  200,  197,  200,
      205,  204,  201,  201,  201,  198,  190,  189,  126,  192,

      192,  192,  199,  126,  218,  219,  201,  201,  201,  188,
      216,  162,  216,  162,  187,  217,  217,  217,  217,  217,
      217,  186,  185,  218,  184,  183,  219,  162,  220,  182,
      220,  181,  162,  221,  221,  221,  201,  201,  201,  217,
      217,  217,  221,  221,  221,  233,  233,  233,  222,  180,
      222,  193,  232,  193,  232,  177,  176,  233,  233,  233,
      175,  221,  221,  221,  222,  174,  173,  193,  173,  222,
      166,  166,  193,  196,  158,  196,  233,  233,  233,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  218,  196,
      218,  148,  147,  146,  196,  145,  144,  143,  142,  141,

       64,  140,  139,  133,  218,   63,  119,  116,  115,  218,
       52,   52,   52,   52,   52,   52,   52,   56,  112,   56,
       56,   56,   56,   56,   63,  111,  106,   63,   63,   63,
       63,   94,   94,   94,  123,  103,  123,  123,  123,  123,
      123,  134,  134,  195,   99,  195,   98,   97,   91,   86,
       65,   64,   55,  237,    5,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237
    } ;

static const flex_int16_t yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   10,   11,   11,   12,
       17,   19,    3,    4,   20,   20,   20,   21,   26,   37,
       19,   17,   21,   28,   28,   12,   37,   31,   41,   21,
       31,   37,   26,   39,   26,   26,   41,   10,   22,   42,

       22,   22,   22,   39,   45,   42,   49,   45,   56,   63,
       75,   22,   79,   77,   22,   77,   22,   22,   77,   77,
       77,   76,   84,   76,   76,   76,   78,   22,   78,  244,
       95,   79,  234,   22,   76,  129,   75,   63,  226,   56,
       22,   84,  225,   22,   23,   49,   23,   23,   23,   83,
       76,   83,   78,   81,   70,   70,   70,   23,  214,  129,
       23,   95,   23,  213,  135,   70,   70,  169,   70,  169,
       81,  212,   85,   23,  211,   83,  209,   81,  208,   23,
      171,   70,   70,   74,   74,   74,   23,   70,  135,   85,
      127,  127,  127,  169,   74,   74,   85,   74,  121,  171,

      121,  145,  145,  121,  121,  121,  124,  124,  124,  207,
       74,   74,  159,  159,  159,  205,   74,  124,  124,  125,
      124,  125,  203,  202,  125,  125,  125,  134,  128,  128,
      128,  190,  188,  124,  124,  160,  160,  160,  187,  124,
      128,  186,  128,  134,  134,  134,  161,  160,  161,  160,
      198,  161,  161,  161,  167,  167,  128,  163,  163,  163,
      185,  128,  134,  160,  183,  134,  168,  168,  160,  134,
      164,  164,  164,  167,  198,  182,  167,  180,  172,  191,
      191,  191,  164,  179,  164,  168,  178,  170,  168,  170,
      175,  174,  170,  170,  170,  172,  158,  157,  164,  192,

      192,  192,  172,  164,  195,  195,  200,  200,  200,  156,
      194,  192,  194,  192,  155,  194,  194,  194,  216,  216,
      216,  154,  153,  195,  151,  150,  195,  192,  197,  148,
      197,  147,  192,  197,  197,  197,  201,  201,  201,  217,
      217,  217,  220,  220,  220,  232,  232,  232,  201,  146,
      201,  217,  219,  217,  219,  144,  143,  219,  219,  219,
      142,  221,  221,  221,  201,  141,  138,  217,  137,  201,
      132,  131,  217,  221,  116,  221,  233,  233,  233,  115,
      114,  113,  112,  111,  110,  108,  107,  106,  233,  221,
      233,  105,  104,  103,  221,  102,  101,  100,   99,   98,

       96,   93,   89,   80,  233,   64,   54,   47,   46,  233,
      238,  238,  238,  238,  238,  238,  238,  239,   44,  239,
      239,  239,  239,  239,  240,   43,   40,  240,  240,  240,
      240,  241,  241,  241,  242,   38,  242,  242,  242,  242,
      242,  243,  243,  245,   36,  245,   35,   34,   27,   24,
       16,   13,    9,    5,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.l"
#line 2 "tokens.l"
#include <string>
#include "node.hpp"
#include <stdio.h>
#include "parser.hpp"

#define TOKEN(t) (yylval.token = t)
#define SAVE_TOKEN yylval.string = new std::string(yytext, yyleng)

extern int debug;
#line 677 "tokens.cpp"

#line 679 "tokens.cpp"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "tokens.l"


#line 31 "tokens.l"
    /* Simbolos de Atribuicao */
#line 902 "tokens.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 238 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 455 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "IGUAL"); return TOKEN(IGUAL);              }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIOR_MAIOR_IGUAL"); return TOKEN(MAIOR_MAIOR_IGUAL);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOR_MENOR_IGUAL"); return TOKEN(MENOR_MENOR_IGUAL);  }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIS_IGUAL"); return TOKEN(MAIS_IGUAL);         }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOS_IGUAL"); return TOKEN(MENOS_IGUAL);        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ASTERISCO_IGUAL"); return TOKEN(ASTERISCO_IGUAL);    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "BARRA_IGUAL"); return TOKEN(BARRA_IGUAL);        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PORCENTAGEM_IGUAL"); return TOKEN(PORCENTAGEM_IGUAL);  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "AMPERSAND_IGUAL"); return TOKEN(AMPERSAND_IGUAL);    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CIRCUNFLEXO_IGUAL"); return TOKEN(CIRCUNFLEXO_IGUAL);  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PIPE_IGUAL"); return TOKEN(PIPE_IGUAL);         }
	YY_BREAK
/* Operadores Aritimeticos */
case 12:
YY_RULE_SETUP
#line 45 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOS"); return TOKEN(MENOS);              }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIS"); return TOKEN(MAIS);               }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ASTERISCO"); return TOKEN(ASTERISCO);          }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "BARRA"); return TOKEN(BARRA);              }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PORCENTAGEM"); return TOKEN(PORCENTAGEM);        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIS_MAIS"); return TOKEN(MAIS_MAIS);          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOS_MENOS"); return TOKEN(MENOS_MENOS);        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIOR_MAIOR"); return TOKEN(MAIOR_MAIOR);        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOR_MENOR"); return TOKEN(MENOR_MENOR);        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CIRCUNFLEXO"); return TOKEN(CIRCUNFLEXO);        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PIPE"); return TOKEN(PIPE);               }
	YY_BREAK
/* Operadores Relacionais */
case 23:
YY_RULE_SETUP
#line 58 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOR_IGUAL"); return TOKEN(MENOR_IGUAL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIOR_IGUAL"); return TOKEN(MAIOR_IGUAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "IGUAL_IGUAL"); return TOKEN(IGUAL_IGUAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "EXCLAMACAO_IGUAL"); return TOKEN(EXCLAMACAO_IGUAL); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MENOR"); return TOKEN(MENOR); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "MAIOR"); return TOKEN(MAIOR); }
	YY_BREAK
/* Operadores Logicos */
case 29:
YY_RULE_SETUP
#line 66 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "AMPERSAND_AMPERSAND"); return TOKEN(AMPERSAND_AMPERSAND); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PIPE_PIPE"); return TOKEN(PIPE_PIPE); }
	YY_BREAK
/* Operadores Unarios */
case 31:
YY_RULE_SETUP
#line 70 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "AMPERSAND"); return TOKEN(AMPERSAND); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "EXCLAMACAO"); return TOKEN(EXCLAMACAO); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "TIL"); return TOKEN(TIL); }
	YY_BREAK
/* Outros Simbolos */
case 34:
YY_RULE_SETUP
#line 75 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ABRE_PARENTESES"); return TOKEN(ABRE_PARENTESES); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "FECHA_PARENTESES"); return TOKEN(FECHA_PARENTESES); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PONTO_VIRGULA"); return TOKEN(PONTO_VIRGULA); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "VIRGULA"); return TOKEN(VIRGULA); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "DOIS_PONTOS"); return TOKEN(DOIS_PONTOS); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ABRE_CHAVES"); return TOKEN(ABRE_CHAVES); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "FECHA_CHAVES"); return TOKEN(FECHA_CHAVES); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ABRE_COLCHETES"); return TOKEN(ABRE_COLCHETES); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "FECHA_COLCHETES"); return TOKEN(FECHA_COLCHETES); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "INTERROGACAO"); return TOKEN(INTERROGACAO); }
	YY_BREAK
/* Palavras Reservadas */
/* Tipos de Dados */
case 44:
YY_RULE_SETUP
#line 89 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CHAR"); return TOKEN(CHAR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "INT"); return TOKEN(INT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "VOID"); return TOKEN(VOID); }
	YY_BREAK
/* Desvio de Execucao */
case 47:
YY_RULE_SETUP
#line 94 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "IF"); return TOKEN(IF); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "ELSE"); return TOKEN(ELSE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "SWITCH"); return TOKEN(SWITCH); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CASE"); return TOKEN(CASE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "DEFAULT"); return TOKEN(DEFAULT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "BREAK"); return TOKEN(BREAK); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONTINUE"); return TOKEN(CONTINUE); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "GOTO"); return TOKEN(GOTO); }
	YY_BREAK
/* Loops */
case 55:
YY_RULE_SETUP
#line 104 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "FOR"); return TOKEN(FOR); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "WHILE"); return TOKEN(WHILE); }
	YY_BREAK
/* Outras Palavras Reservadas */
case 57:
YY_RULE_SETUP
#line 109 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "BOOL"); return TOKEN(BOOL); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONST"); return TOKEN(CONST); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "EXTERN"); return TOKEN(EXTERN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "RETURN"); return TOKEN(RETURN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "STATIC"); return TOKEN(STATIC); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "BREAKP"); return TOKEN(BREAKP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "GETCH"); return TOKEN(GETCH); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "PRINTF"); return TOKEN(PRINTF); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "IDENTIFIER"); return IDENTIFIER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 121 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 122 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 123 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 126 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 127 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 129 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 130 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 131 "tokens.l"
{ SAVE_TOKEN; if(debug) printf("@(%d): achou %s - %s\n", yylineno, yytext, "CONSTANT"); return CONSTANT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 134 "tokens.l"
{   //SAVE_TOKEN; 

                                yylval.string = new std::string(yytext, 1, yyleng-2);
                                if(debug) 
                                    printf("@(%d): achou %s - %s\n", yylineno, yytext, "STRING_LITERAL"); 
                                //yylval.string->erase(yylval.string->begin());
                                //yylval.string->erase(yylval.string->end());
                                return STRING_LITERAL; 
                            }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 144 "tokens.l"
{ }
	YY_BREAK
/* comments */
case 78:
YY_RULE_SETUP
#line 147 "tokens.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "tokens.l"

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "tokens.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 151 "tokens.l"
{ return 1;  }
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 152 "tokens.l"
{ }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 153 "tokens.l"

	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 154 "tokens.l"
{ yyterminate(); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 155 "tokens.l"
{ }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 157 "tokens.l"
ECHO;
	YY_BREAK
#line 1418 "tokens.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 238 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 238 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 237);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 157 "tokens.l"


/* A Bison parser, made by GNU Bison 3.6.4.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2020 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_YY_PARSER_HPP_INCLUDED
# define YY_YY_PARSER_HPP_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 1
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    YYEOF = 0,                     /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    STRING_LITERAL = 258,          /* STRING_LITERAL  */
    IDENTIFIER = 259,              /* IDENTIFIER  */
    CONSTANT = 260,                /* CONSTANT  */
    MENOR = 261,                   /* MENOR  */
    MAIOR = 262,                   /* MAIOR  */
    MENOR_IGUAL = 263,             /* MENOR_IGUAL  */
    MAIOR_IGUAL = 264,             /* MAIOR_IGUAL  */
    IGUAL_IGUAL = 265,             /* IGUAL_IGUAL  */
    EXCLAMACAO_IGUAL = 266,        /* EXCLAMACAO_IGUAL  */
    AMPERSAND_AMPERSAND = 267,     /* AMPERSAND_AMPERSAND  */
    PIPE_PIPE = 268,               /* PIPE_PIPE  */
    EXCLAMACAO = 269,              /* EXCLAMACAO  */
    IGUAL = 270,                   /* IGUAL  */
    MAIS_IGUAL = 271,              /* MAIS_IGUAL  */
    MENOS_IGUAL = 272,             /* MENOS_IGUAL  */
    ASTERISCO_IGUAL = 273,         /* ASTERISCO_IGUAL  */
    BARRA_IGUAL = 274,             /* BARRA_IGUAL  */
    MAIOR_MAIOR_IGUAL = 275,       /* MAIOR_MAIOR_IGUAL  */
    MENOR_MENOR_IGUAL = 276,       /* MENOR_MENOR_IGUAL  */
    PORCENTAGEM_IGUAL = 277,       /* PORCENTAGEM_IGUAL  */
    CIRCUNFLEXO_IGUAL = 278,       /* CIRCUNFLEXO_IGUAL  */
    AMPERSAND_IGUAL = 279,         /* AMPERSAND_IGUAL  */
    PIPE_IGUAL = 280,              /* PIPE_IGUAL  */
    VOID = 281,                    /* VOID  */
    INT = 282,                     /* INT  */
    CHAR = 283,                    /* CHAR  */
    BOOL = 284,                    /* BOOL  */
    IF = 285,                      /* IF  */
    ELSE = 286,                    /* ELSE  */
    FOR = 287,                     /* FOR  */
    WHILE = 288,                   /* WHILE  */
    BREAK = 289,                   /* BREAK  */
    SWITCH = 290,                  /* SWITCH  */
    CASE = 291,                    /* CASE  */
    CONTINUE = 292,                /* CONTINUE  */
    INCLUDE = 293,                 /* INCLUDE  */
    GOTO = 294,                    /* GOTO  */
    RETURN = 295,                  /* RETURN  */
    CONST = 296,                   /* CONST  */
    DEFAULT = 297,                 /* DEFAULT  */
    EXTERN = 298,                  /* EXTERN  */
    STATIC = 299,                  /* STATIC  */
    MAIS = 300,                    /* MAIS  */
    MENOS = 301,                   /* MENOS  */
    MAIS_MAIS = 302,               /* MAIS_MAIS  */
    MENOS_MENOS = 303,             /* MENOS_MENOS  */
    ASTERISCO = 304,               /* ASTERISCO  */
    BARRA = 305,                   /* BARRA  */
    PORCENTAGEM = 306,             /* PORCENTAGEM  */
    CIRCUNFLEXO = 307,             /* CIRCUNFLEXO  */
    DOIS_PONTOS = 308,             /* DOIS_PONTOS  */
    VIRGULA = 309,                 /* VIRGULA  */
    PONTO_VIRGULA = 310,           /* PONTO_VIRGULA  */
    INTERROGACAO = 311,            /* INTERROGACAO  */
    SUSTENIDO = 312,               /* SUSTENIDO  */
    ABRE_COLCHETES = 313,          /* ABRE_COLCHETES  */
    FECHA_COLCHETES = 314,         /* FECHA_COLCHETES  */
    ABRE_PARENTESES = 315,         /* ABRE_PARENTESES  */
    FECHA_PARENTESES = 316,        /* FECHA_PARENTESES  */
    ABRE_CHAVES = 317,             /* ABRE_CHAVES  */
    FECHA_CHAVES = 318,            /* FECHA_CHAVES  */
    MENOR_MENOR = 319,             /* MENOR_MENOR  */
    MAIOR_MAIOR = 320,             /* MAIOR_MAIOR  */
    PIPE = 321,                    /* PIPE  */
    AMPERSAND = 322,               /* AMPERSAND  */
    TIL = 323,                     /* TIL  */
    BREAKP = 324,                  /* BREAKP  */
    GETCH = 325,                   /* GETCH  */
    PRINTF = 326,                  /* PRINTF  */
    UNSIGNED = 327,                /* UNSIGNED  */
    UNION = 328,                   /* UNION  */
    TYPE_NAME = 329,               /* TYPE_NAME  */
    TYPEDEF = 330,                 /* TYPEDEF  */
    STRUCT = 331,                  /* STRUCT  */
    SIZEOF = 332,                  /* SIZEOF  */
    SIGNED = 333,                  /* SIGNED  */
    RESTRICT = 334,                /* RESTRICT  */
    REGISTER = 335,                /* REGISTER  */
    INLINE = 336,                  /* INLINE  */
    IMAGINARY = 337,               /* IMAGINARY  */
    ELLIPSIS = 338,                /* ELLIPSIS  */
    DO = 339,                      /* DO  */
    COMPLEX = 340,                 /* COMPLEX  */
    AUTO = 341,                    /* AUTO  */
    VOLATILE = 342,                /* VOLATILE  */
    ENUM = 343,                    /* ENUM  */
    PONTO = 344,                   /* PONTO  */
    DOUBLE = 345,                  /* DOUBLE  */
    SHORT = 346,                   /* SHORT  */
    LONG = 347,                    /* LONG  */
    FLOAT = 348                    /* FLOAT  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
union YYSTYPE
{
#line 141 "parser.y"

    int token;
    std::string *string;

#line 162 "parser.hpp"

};
typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_PARSER_HPP_INCLUDED  */

